# Generated by Django 3.1.5 on 2021-01-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=255)),
                ('contact_number', models.BigIntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
