# Generated by Django 3.1.5 on 2021-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=255)),
                ('contact_number', models.BigIntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
