# Generated by Django 3.1.5 on 2021-01-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_repo', '0003_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='standard',
            field=models.IntegerField(),
        ),
    ]
